services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    DigipolisGent\Domainator9k\CoreBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests}'
    DigipolisGent\Domainator9k\CoreBundle\EventListener\EnvironmentEventListener:
        tags:
            - { name: doctrine.event_listener, event: postPersist, connection: default }
            - { name: doctrine.event_listener, event: postRemove, connection: default }
    DigipolisGent\Domainator9k\CoreBundle\Service\TemplateService:
        arguments:
            $templateProviders: !tagged template_provider
    DigipolisGent\Domainator9k\CoreBundle\Service\TaskRunnerService:
        arguments:
            - !tagged domainator.provisioner.build
            - !tagged domainator.provisioner.destroy
    DigipolisGent\Domainator9k\CoreBundle\Twig\TemplateHelpExtension:
        tags: [twig.extension]
    DigipolisGent\Domainator9k\CoreBundle\Provisioner\CacheClearBuildProvisioner:
        tags:
            - {name: domainator.provisioner.build, priority: -90}
    DigipolisGent\Domainator9k\CoreBundle\Provider\CliFactoryProvider:
        arguments:
            - '@DigipolisGent\Domainator9k\CoreBundle\CLI\DefaultCliFactory'

